apiVersion: apps/v1
kind: Deployment
metadata:
  name: trung-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trung-python-deployment
  template:
    metadata:
      labels:
        app: trung-python-deployment
    spec:
      containers:
      - name: trung-python
        image: trungtien/python:latest
        ports:
        - containerPort: 1313

---
apiVersion: v1
kind: Service
metadata:
  name: trung-python-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
    nodePort: 32224
  selector:
    app: trung-python-deployment
  type: LoadBalancer
